services:

  backend:
    build:
      context: .
    volumes:
      - ./mount/:/backend/mount
    # command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    command: python -m uv run main.py
    env_file:
      - ./.env
    ports:
      - 8000:8800
    depends_on:
      - dbserver

    stdin_open: true
    tty: true

  dbserver:
    image: postgres:latest
    volumes:
      - ./mount/:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432
